version: '3.9'

services:
  app:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./data:/opt/comfort_chatbot/data
      - ./models:/opt/comfort_chatbot/models
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data


